name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: [self-hosted]
    env:
      CONTAINER_NAME: frontendContainer
      IMAGE_NAME: fe_tixclick:latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3

 
      # Build Docker image
      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t ${{ env.IMAGE_NAME }} -f ./dockerfile .

      # Stop và remove container cũ nếu tồn tại
      - name: Stop and Remove Existing Container if Any
        run: |
          CNAME=${{ env.CONTAINER_NAME }}
          if [ "$(docker ps -aq -f name=$CNAME)" ]; then
              echo "Stopping and removing existing container - $CNAME"
              docker stop $CNAME
              docker rm $CNAME
          else
              echo "No existing container to stop."
          fi

      # Run container mới
      - name: Run New Docker Container
        run: |
          CNAME=${{ env.CONTAINER_NAME }}
          echo "Running new frontend container - $CNAME"
          docker run -d -p 5173:5173 --name $CNAME ${{ env.IMAGE_NAME }}

      # Cleanup các image/volume không dùng
      - name: Cleanup Unused Docker Resources
        run: |
          echo "Cleaning up unused Docker images and volumes..."
          docker system prune -af --volumes
