name: Build and Run HTML Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-run:
    runs-on: self-hosted  # dùng VPS runner của bạn

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t my-html-site .

    - name: Run Docker container
      run: |
        docker stop html-site || true
        docker rm html-site || true
        docker run -d --name html-site -p 80:80 my-html-site
